import random
from attack_dict import attack_dict
from type_chart_factor import type_bonus_dict

def type_bonus(key: str, defender) -> int:
    """
    Returns the integer of the type bonus an attack has on any specific Pokemon.
    :param key: The attack key for the attack dictionary
    :param defender: The defending Pokemon
    :return: Integer of percentage bonus, 1 = 100%
    """
    if str(attack_dict[key][0]) + str(defender.type_1) in type_bonus_dict:
        bonus_1 = type_bonus_dict[str(attack_dict[key][0]) + str(defender.type_1)]
        if str(attack_dict[key][0]) + str(defender.type_2) in type_bonus_dict:
            bonus_2 = type_bonus_dict[str(attack_dict[key][0]) + str(defender.type_1)] * type_bonus_dict[str(attack_dict[key][0]) + str(defender.type_2)]
            return bonus_2
        return bonus_1
    else:
        return 1

class Pokemon:
    def __init__(self, name, evo, type_1, type_2, hp, att,
                 deff, spd, a1, a2, a3, a4):
        self.name = name
        self.evo = evo
        self.type_1 = type_1
        self.type_2 = type_2
        self.hp_1 = hp
        self.atk_stat = att
        self.deff = deff
        self.spd = spd
        self.lvl = 1
        self.health = round((1 + ((self.lvl - 1) /10)) *150 * (hp/100))
        self.max_health = round((1 + ((self.lvl - 1) /10)) *150 * (hp/100))
        self.atk_1 = a1
        self.atk_2 = a2
        self.atk_3 = a3
        self.atk_4 = a4
        self.att_key = [a1, a2, a3, a4, "DELETE"]



    def attack(self, player_2, key):
        dmg_pre = round(self.atk_stat * attack_dict[key][1] / random.randint(200, 300))
        dmg_out = round(((1 + ((self.lvl - 1) /10)) * (dmg_pre * 0.5) + (dmg_pre * (0.5 * (player_2.deff/300)))) * float(type_bonus(key, player_2)))
        player_2.health -= dmg_out
        # print(dmg_pre)
        # print(dmg_out)
        print(f"{self.name} used {key} on {player_2.name}! [{dmg_out}]")
        if float(type_bonus(key, player_2)) > 1.5:
            print("Its super effective!")
        elif float(type_bonus(key, player_2)) == 0:
            print(f"{player_2.name} is immune to {key}")
        elif float(type_bonus(key, player_2)) < 1:
            print("Its not very effective!")
        # + str(player_2.health) + " " + str(dmg_out))



# ALL LITTLE CUP POKEMON WAS GENERATED BY CHATGPT

# Little Cup (SS) — unevolved Pokémon that can evolve
# Pokemon(name, None, type1, type2_or_None, HP, max(Atk,SpA), max(Def,SpD), Spe, move1, move2, move3, move4)

Mienfoo = Pokemon("Mienfoo", None, "Fighting", None,
                  45, 85, 50, 65, "Drain Punch",
                  "Brick Break", "Knock Off", "U-turn")

Ferroseed = Pokemon("Ferroseed", None, "Grass", "Steel",
                    44, 50, 91, 10, "Power Whip",
                    "Anchor Shot", "Gyro Ball", "Rock Throw")

Pawniard = Pokemon("Pawniard", None, "Dark", "Steel",
                   45, 85, 70, 60, "Knock Off",
                   "Iron Head", "Sucker Punch", "Night Slash")

Staryu = Pokemon("Staryu", None, "Water", None,
                 30, 70, 55, 85, "Hydro Pump",
                 "Water Pulse", "Ice Beam", "Thunder Shock")

Onix = Pokemon("Onix", None, "Rock", "Ground",
               35, 45, 160, 70, "Rock Slide",
               "Smack Down", "Earthquake", "Dragon Tail")

Foongus = Pokemon("Foongus", None, "Grass", "Poison",
                  69, 55, 55, 15, "Giga Drain",
                  "Energy Ball", "Sludge Wave", "Clear Smog")

Koffing = Pokemon("Koffing", None, "Poison", None,
                  40, 65, 95, 35, "Sludge Wave",
                  "Incinerate", "Clear Smog", "Dark Pulse")

Ponyta = Pokemon("Ponyta", None, "Fire", None,
                 50, 85, 65, 90, "Flame Charge",
                 "Fire Blast", "Bounce", "Stomp")

Ponyta_G = Pokemon("Galarian Ponyta", None, "Psychic", None,
                   50, 85, 65, 90, "Zen Headbutt",
                   "Psyshock", "Psybeam", "Swift")

Timburr = Pokemon("Timburr", None, "Fighting", None,
                  75, 80, 55, 35, "Drain Punch",
                  "Brick Break", "Mach Punch", "Rock Slide")

Spritzee = Pokemon("Spritzee", None, "Fairy", None,
                   78, 63, 65, 23, "Dazzling Gleam",
                   "Draining Kiss", "Energy Ball", "Psychic")

Mareanie = Pokemon("Mareanie", None, "Poison", "Water",
                   50, 53, 62, 45, "Scald",
                   "Sludge Wave", "Brine", "Poison Jab")

Frillish = Pokemon("Frillish", None, "Water", "Ghost",
                   55, 65, 85, 40, "Scald",
                   "Hex", "Water Pulse", "Shadow Ball")

Natu = Pokemon("Natu", None, "Psychic", "Flying",
               40, 70, 45, 70, "Air Slash",
               "Psyshock", "U-turn", "Dazzling Gleam")

Mudbray = Pokemon("Mudbray", None, "Ground", None,
                  70, 100, 70, 45, "Earthquake",
                  "Rock Slide", "Double-Edge", "Stomp")

Grookey = Pokemon("Grookey", None, "Grass", None,
                  50, 65, 50, 65, "Grassy Glide",
                  "Leaf Blade", "U-turn", "Knock Off")

Abra = Pokemon("Abra", None, "Psychic", None,
               25, 105, 55, 90, "Psychic",
               "Psyshock", "Dazzling Gleam", "Energy Ball")

Magnemite = Pokemon("Magnemite", None, "Electric", "Steel",
                    25, 95, 70, 45, "Discharge",
                    "Volt Switch", "Flash Cannon", "Tri Attack")

Diglett = Pokemon("Diglett", None, "Ground", None,
                  10, 55, 45, 95, "Earthquake",
                  "Rock Slide", "Sucker Punch", "Slash")

Stunky = Pokemon("Stunky", None, "Poison", "Dark",
                 63, 63, 47, 74, "Poison Jab",
                 "Night Slash", "Bite", "Explosion")

Gastly = Pokemon("Gastly", None, "Ghost", "Poison",
                 30, 100, 35, 80, "Hex",
                 "Sludge Wave", "Dark Pulse", "Energy Ball")

Carvanha = Pokemon("Carvanha", None, "Water", "Dark",
                   45, 90, 20, 65, "Liquidation",
                   "Aqua Jet", "Crunch", "Ice Fang")

Dwebble = Pokemon("Dwebble", None, "Bug", "Rock",
                  50, 65, 85, 55, "Rock Blast",
                  "Bug Bite", "Smack Down", "X-Scissor")

Munchlax = Pokemon("Munchlax", None, "Normal", None,
                   135, 85, 85, 5, "Body Slam",
                   "Crunch", "Fire Punch", "Ice Punch")

Rufflet = Pokemon("Rufflet", None, "Normal", "Flying",
                  70, 83, 50, 60, "Brave Bird",
                  "Aerial Ace", "Rock Slide", "U-turn")

Larvesta = Pokemon("Larvesta", None, "Bug", "Fire",
                   55, 85, 55, 60, "Flame Charge",
                   "Bug Bite", "U-turn", "Leech Life")

Snover = Pokemon("Snover", None, "Grass", "Ice",
                 60, 62, 60, 40, "Blizzard",
                 "Ice Shard", "Giga Drain", "Energy Ball")

Sandshrew_A = Pokemon("Alolan Sandshrew", None, "Ice", "Steel",
                      50, 75, 90, 40, "Icicle Crash",
                      "Metal Claw", "Ice Shard", "Rock Slide")

Vulpix = Pokemon("Vulpix", None, "Fire", None,
                 38, 65, 75, 65, "Flame Burst",
                 "Incinerate", "Extrasensory", "Dark Pulse")

Vulpix_A = Pokemon("Alolan Vulpix", None, "Ice", None,
                   38, 65, 75, 65, "Blizzard",
                   "Ice Beam", "Aurora Beam", "Icy Wind")

Corphish = Pokemon("Corphish", None, "Water", None,
                   43, 80, 55, 35, "Crabhammer",
                   "Aqua Jet", "Razor Shell", "Knock Off")

Zigzagoon_G = Pokemon("Galarian Zigzagoon", None, "Dark", "Normal",
                      38, 80, 41, 60, "Knock Off",
                      "Night Slash", "Headbutt", "Seed Bomb")

Hatenna = Pokemon("Hatenna", None, "Psychic", None,
                  42, 86, 65, 34, "Psychic",
                  "Psybeam", "Dazzling Gleam", "Mystical Fire")

Baltoy = Pokemon("Baltoy", None, "Ground", "Psychic",
                 40, 40, 80, 55, "Earth Power",
                 "Psybeam", "Rock Tomb", "Ancient Power")

Buizel = Pokemon("Buizel", None, "Water", None,
                 55, 65, 55, 85, "Waterfall",
                 "Aqua Jet", "Ice Fang", "Swift")

Clauncher = Pokemon("Clauncher", None, "Water", None,
                    50, 71, 63, 44, "Water Pulse",
                    "Aqua Jet", "Crabhammer", "Dark Pulse")

Drilbur = Pokemon("Drilbur", None, "Ground", None,
                  60, 85, 45, 68, "Earthquake",
                  "Rock Slide", "Rapid Spin", "Slash")

Elekid = Pokemon("Elekid", None, "Electric", None,
                 45, 63, 55, 95, "Discharge",
                 "Thunder Shock", "Ice Punch", "Brick Break")

Fletchling = Pokemon("Fletchling", None, "Normal", "Flying",
                     45, 50, 50, 62, "Brave Bird",
                     "Aerial Ace", "Quick Attack", "U-turn")

Golett = Pokemon("Golett", None, "Ground", "Ghost",
                 59, 74, 80, 35, "Shadow Punch",
                 "Brick Break", "Earthquake", "Rock Slide")

Hippopotas = Pokemon("Hippopotas", None, "Ground", None,
                     68, 72, 78, 32, "Earthquake",
                     "Rock Slide", "Body Slam", "Bite")

Kabuto = Pokemon("Kabuto", None, "Rock", "Water",
                 30, 80, 90, 55, "Aqua Jet",
                 "Rock Slide", "Razor Shell", "Ancient Power")

Krabby = Pokemon("Krabby", None, "Water", None,
                 30, 105, 90, 50, "Crabhammer",
                 "Aqua Jet", "Rock Slide", "Body Slam")

Lileep = Pokemon("Lileep", None, "Rock", "Grass",
                 66, 61, 87, 23, "Giga Drain",
                 "Ancient Power", "Energy Ball", "Mirror Shot")

Machop = Pokemon("Machop", None, "Fighting", None,
                 70, 80, 60, 35, "Brick Break",
                 "Dynamic Punch", "Bullet Punch", "Rock Slide")

Mankey = Pokemon("Mankey", None, "Fighting", None,
                 40, 80, 50, 70, "Brick Break",
                 "Low Sweep", "U-turn", "Poison Jab")

Nosepass = Pokemon("Nosepass", None, "Rock", None,
                   30, 45, 135, 30, "Power Gem",
                   "Rock Slide", "Thunder Shock", "Smack Down")

Oshawott = Pokemon("Oshawott", None, "Water", None,
                   55, 63, 60, 45, "Razor Shell",
                   "Aqua Jet", "Water Pulse", "Night Slash")

Pancham = Pokemon("Pancham", None, "Fighting", None,
                  67, 82, 62, 43, "Brick Break",
                  "Drain Punch", "Dark Pulse", "Poison Jab")

Remoraid = Pokemon("Remoraid", None, "Water", None,
                   35, 65, 45, 65, "Hydro Pump",
                   "Ice Beam", "Water Pulse", "Bullet Seed")

Shellder = Pokemon("Shellder", None, "Water", None,
                   30, 65, 100, 40, "Icicle Spear",
                   "Ice Shard", "Razor Shell", "Waterfall")

Skorupi = Pokemon("Skorupi", None, "Poison", "Bug",
                  40, 60, 90, 65, "Poison Jab",
                  "Bug Bite", "Knock Off", "Night Slash")

Tentacool = Pokemon("Tentacool", None, "Water", "Poison",
                    40, 50, 65, 70, "Scald",
                    "Acid Spray", "Sludge Wave", "Water Pulse")

Tirtouga = Pokemon("Tirtouga", None, "Water", "Rock",
                   54, 78, 103, 22, "Aqua Jet",
                   "Waterfall", "Rock Slide", "Crunch")

Trapinch = Pokemon("Trapinch", None, "Ground", None,
                   45, 100, 45, 10, "Earthquake",
                   "Crunch", "Rock Slide", "Superpower")

Tyrogue = Pokemon("Tyrogue", None, "Fighting", None,
                  35, 35, 35, 35, "Tackle",
                  "Mach Punch", "Bullet Punch", "Vacuum Wave")

Zorua_H = Pokemon("Hisuian Zorua", None, "Normal", "Ghost",
                  35, 85, 60, 60, "Hex",
                  "Shadow Sneak", "Swift", "Bite")

# ----------------------------
# LC master list
# ----------------------------
LC_Poke = [
    Mienfoo, Ferroseed, Pawniard, Staryu, Onix, Foongus, Koffing, Ponyta, Ponyta_G,
    Timburr, Spritzee, Mareanie, Frillish, Natu, Mudbray, Grookey, Abra, Magnemite,
    Diglett, Stunky, Gastly, Carvanha, Dwebble, Munchlax, Rufflet, Larvesta, Snover,
    Sandshrew_A, Vulpix, Vulpix_A, Corphish, Zigzagoon_G, Hatenna, Baltoy, Buizel,
    Clauncher, Drilbur, Elekid, Fletchling, Golett, Hippopotas, Kabuto, Krabby,
    Lileep, Machop, Mankey, Nosepass, Oshawott, Pancham, Remoraid, Shellder, Skorupi,
    Tentacool, Tirtouga, Trapinch, Tyrogue, Zorua_H
]


# xxxxxxxxxxxxxxxxxxxxxxxx

Metagross = Pokemon("Metagross", None, "Steel", "Psychic",
                    80, 135, 130, 70, "Bullet Punch",
                    "Psychic", "Earthquake", "Sludge Bomb")

Escavalier = Pokemon("Escavalier", None, "Bug", "Steel",
                     10, 135, 105, 20, "X-Scissor",
                     "Iron Head", "Close Combat", "Drill Run")

Jolteon = Pokemon("Jolteon", None, "Electric", None,
                  65, 110, 95, 130, "Thunder",
                  "Shadow Ball", "Double Edge", "Dig")

Medicham = Pokemon("Medicham", None, "Fighting",
                   "Psychic", 60, 60, 75, 80,
                   "Close Combat", "Ice Punch", "Thunder Punch",
                   "Fire Punch")

Mismagius = Pokemon("Mismagius", None, "Ghost", None,
                    60, 105, 105, 105,"Shadow Ball",
                    "Psychic", "Thunder","Magical Leaf")

Clawitzer = Pokemon("Clawitzer", None, "Water", None,
                    71, 120, 89, 59, "Hydropump",
                    "Hyper Beam", "Aura Sphere", "Ice Beam")

Exeggutor_A = Pokemon("Alolan Exeggutor", None, "Grass",
                      "Dragon", 95, 125, 85, 45,
                      "Draco Meteor", "Leaf Storm", "Giga Impact",
                      "Earthquake")

Avalugg_H =Pokemon("Hisuian Avalugg", None, "Ice", "Rock",
                   95, 127, 184, 38, "Stone Edge",
                   "Earthquake", "Mountain Gale", "Giga Impact")

Blissey = Pokemon("Blissey", None, "Normal", None,
                  255, 75, 135, 55, "Hyper Beam",
                  "Shadow Ball", "Thunder", "Psychic")

Hariyama = Pokemon("Hariyama", None, "Fighting", None,
                   144, 120, 50, 50, "Close Combat",
                   "Surf", "Stone Edge", "Poison Jab")

Hoopa_U = Pokemon("Hoopa, Unbound", None, "Psychic", "Dark",
                  80, 170, 130, 80, "Focus Punch",
                  "Giga Impact", "Hyperspace Fury", "Future Sight")

# ALL POKEMON FROM THIS POINT WAS GENERATED BY CHATGPT

Abomasnow = Pokemon("Abomasnow", None, "Grass", "Ice",
                    90, 92, 85, 60, "Blizzard",
                    "Giga Drain", "Wood Hammer", "Ice Shard")

Ambipom = Pokemon("Ambipom", None, "Normal", None,
                  75, 100, 66, 115, "Fake Out",
                  "Double Hit", "U-turn", "Knock Off")

Amoonguss = Pokemon("Amoonguss", None, "Grass", "Poison",
                    114, 85, 80, 30, "Giga Drain",
                    "Sludge Wave", "Clear Smog", "Energy Ball")

Arcanine = Pokemon("Arcanine", None, "Fire", None,
                   90, 110, 80, 95, "Fire Blast",
                   "Extreme Speed", "Wild Charge", "Brick Break")

Appletun = Pokemon("Appletun", None, "Grass", "Dragon",
                   110, 100, 80, 30, "Grav Apple",
                   "Dragon Pulse", "Energy Ball", "Giga Drain")

Avalugg = Pokemon("Avalugg", None, "Ice", None,
                  95, 117, 184, 28, "Icicle Crash",
                  "Avalanche", "Body Press", "Bulldoze")


Azumarill = Pokemon("Azumarill", None, "Water", "Fairy",
                    100, 60, 80, 50, "Play Rough",
                    "Waterfall", "Aqua Jet", "Superpower")

Banette = Pokemon("Banette", None, "Ghost", None,
                  64, 115, 65, 65, "Shadow Punch",
                  "Shadow Sneak", "Knock Off", "Night Slash")

Barraskewda = Pokemon("Barraskewda", None, "Water", None,
                      61, 123, 60, 136, "Liquidation",
                      "Flip Turn", "Psychic Fangs", "Aqua Jet")

Bellibolt = Pokemon("Bellibolt", None, "Electric", None,
                    109, 103, 91, 45, "Discharge",
                    "Volt Switch", "Parabolic Charge", "Muddy Water")

Bombirdier = Pokemon("Bombirdier", None, "Flying", "Dark",
                     70, 103, 85, 82, "Brave Bird",
                     "Knock Off", "Dual Wingbeat", "Rock Throw")

Braviary = Pokemon("Braviary", None, "Normal", "Flying",
                   100, 123, 75, 80, "Brave Bird",
                   "Drill Peck", "U-turn", "Facade")

Braviary_H = Pokemon("Hisuian Braviary", None, "Psychic", "Flying",
                     110, 112, 70, 65, "Hurricane",
                     "Air Slash", "Psyshock", "Extrasensory")

Bruxish = Pokemon("Bruxish", None, "Water", "Psychic",
                  68, 105, 70, 92, "Psychic Fangs",
                  "Liquidation", "Aqua Jet", "Bite")

Basculegion = Pokemon("Basculegion", None, "Water", "Ghost",
                      120, 112, 75, 78, "Liquidation",
                      "Aqua Jet", "Shadow Sneak", "Poltergeist")

Cacturne = Pokemon("Cacturne", None, "Grass", "Dark",
                   70, 115, 60, 55, "Seed Bomb",
                   "Sucker Punch", "Drain Punch", "Night Slash")

Camerupt = Pokemon("Camerupt", None, "Fire", "Ground",
                   70, 105, 75, 40, "Earth Power",
                   "Lava Plume", "Ancient Power", "Eruption")

Carbink = Pokemon("Carbink", None, "Rock", "Fairy",
                  50, 50, 150, 50, "Power Gem",
                  "Dazzling Gleam", "Ancient Power", "Rock Throw")

Chandelure = Pokemon("Chandelure", None, "Ghost", "Fire",
                     60, 145, 90, 80, "Hex",
                     "Fire Blast", "Mystical Fire", "Energy Ball")

Crabominable = Pokemon("Crabominable", None, "Fighting", "Ice",
                       97, 132, 77, 43, "Ice Hammer",
                       "Hammer Arm", "Avalanche", "Dynamic Punch")

Decidueye = Pokemon("Decidueye", None, "Grass", "Ghost",
                    78, 107, 100, 70, "Leaf Blade",
                    "Brave Bird", "Shadow Sneak", "Energy Ball")

Decidueye_H = Pokemon("Hisuian Decidueye", None, "Grass", "Fighting",
                      88, 112, 95, 60, "Leaf Blade",
                      "Brave Bird", "Brick Break", "Drain Punch")

Drifblim = Pokemon("Drifblim", None, "Ghost", "Flying",
                   150, 90, 54, 80, "Hex",
                   "Air Slash", "Hurricane", "Shadow Sneak")

Dondozo = Pokemon("Dondozo", None, "Water", None,
                  150, 100, 115, 35, "Waterfall",
                  "Body Press", "Body Slam", "Bulldoze")

Espeon = Pokemon("Espeon", None, "Psychic", None,
                 65, 130, 95, 110, "Psyshock",
                 "Psybeam", "Dazzling Gleam", "Swift")

Umbreon = Pokemon("Umbreon", None, "Dark", None,
                  95, 65, 130, 65, "Foul Play",
                  "Assurance", "Snarl", "Bite")

Glaceon = Pokemon("Glaceon", None, "Ice", None,
                  65, 130, 110, 65, "Blizzard",
                  "Freeze-Dry", "Aurora Beam", "Icy Wind")

Leafeon = Pokemon("Leafeon", None, "Grass", None,
                  65, 110, 130, 95, "Leaf Blade",
                  "Quick Attack", "Bug Bite", "Razor Leaf")

Vaporeon = Pokemon("Vaporeon", None, "Water", None,
                   130, 110, 95, 65, "Hydro Pump",
                   "Scald", "Water Pulse", "Aurora Beam")

Electrode = Pokemon("Electrode", None, "Electric", None,
                    60, 80, 80, 150, "Discharge",
                    "Volt Switch", "Charge Beam", "Self-Destruct")

Espathra = Pokemon("Espathra", None, "Psychic", None,
                   95, 101, 60, 105, "Psyshock",
                   "Extrasensory", "Dazzling Gleam", "Air Slash")

Feraligatr = Pokemon("Feraligatr", None, "Water", None,
                     85, 105, 100, 78, "Waterfall",
                     "Ice Fang", "Superpower", "Aqua Jet")

Florges = Pokemon("Florges", None, "Fairy", None,
                  78, 112, 154, 75, "Dazzling Gleam",
                  "Energy Ball", "Draining Kiss", "Misty Explosion")

Floatzel = Pokemon("Floatzel", None, "Water", None,
                   85, 105, 55, 115, "Waterfall",
                   "Aqua Jet", "Flip Turn", "Ice Fang")


Gardevoir = Pokemon("Gardevoir", None, "Psychic", "Fairy",
                    68, 125, 115, 80, "Psyshock",
                    "Dazzling Gleam", "Energy Ball", "Mystical Fire")

Gallade = Pokemon("Gallade", None, "Psychic", "Fighting",
                  68, 125, 115, 80, "Close Combat",
                  "Psycho Cut", "Brick Break", "Night Slash")

Gyarados = Pokemon("Gyarados", None, "Water", "Flying",
                   95, 125, 100, 81, "Waterfall",
                   "Bounce", "Crunch", "Dragon Tail")

Haxorus = Pokemon("Haxorus", None, "Dragon", None,
                  76, 147, 90, 97, "Dragon Claw",
                  "Dragon Rush", "Night Slash", "Iron Tail")

Hatterene = Pokemon("Hatterene", None, "Psychic", "Fairy",
                    57, 136, 103, 29, "Dazzling Gleam",
                    "Psyshock", "Mystical Fire", "Draining Kiss")

Incineroar = Pokemon("Incineroar", None, "Fire", "Dark",
                     95, 115, 90, 60, "Darkest Lariat",
                     "Flare Blitz", "Brick Break", "Snarl")

Kilowattrel = Pokemon("Kilowattrel", None, "Electric", "Flying",
                      70, 105, 70, 125, "Hurricane",
                      "Volt Switch", "Discharge", "Air Slash")

Lanturn = Pokemon("Lanturn", None, "Water", "Electric",
                  125, 76, 76, 67, "Discharge",
                  "Scald", "Ice Beam", "Water Pulse")

Kommo_o = Pokemon("Kommo-o", None, "Dragon", "Fighting",
                  75, 110, 125, 85, "Dragon Claw",
                  "Brick Break", "Dragon Tail", "Body Press")

Krookodile = Pokemon("Krookodile", None, "Ground", "Dark",
                     95, 117, 92, 92, "Earthquake",
                     "Crunch", "Stone Edge", "Assurance")

Lucario = Pokemon("Lucario", None, "Fighting", "Steel",
                  70, 115, 90, 90, "Aura Sphere",
                  "Flash Cannon", "Brick Break", "Extreme Speed")

Lurantis = Pokemon("Lurantis", None, "Grass", None,
                   70, 105, 90, 45, "Leaf Blade",
                   "Solar Blade", "X-Scissor", "Night Slash")

Mabosstiff = Pokemon("Mabosstiff", None, "Dark", None,
                     80, 120, 90, 85, "Crunch",
                     "Assurance", "Psychic Fangs", "Play Rough")


Milotic = Pokemon("Milotic", None, "Water", None,
                  95, 100, 125, 81, "Scald",
                  "Ice Beam", "Hydro Pump", "Dragon Tail")


Magnezone = Pokemon("Magnezone", None, "Electric", "Steel",
                    70, 130, 115, 60, "Discharge",
                    "Flash Cannon", "Volt Switch", "Tri Attack")

Manectric = Pokemon("Manectric", None, "Electric", None,
                    70, 135, 80, 105, "Thunderbolt",
                    "Volt Switch", "Discharge", "Flamethrower")

Mimikyu = Pokemon("Mimikyu", None, "Ghost", "Fairy",
                  55, 90, 105, 96, "Play Rough",
                  "Shadow Sneak", "Drain Punch", "Night Slash")

Muk = Pokemon("Muk", None, "Poison", None,
              105, 105, 100, 50, "Gunk Shot",
              "Poison Jab", "Shadow Sneak", "Body Slam")

Muk_A = Pokemon("Alolan Muk", None, "Poison", "Dark",
                105, 105, 100, 50, "Gunk Shot",
                "Crunch", "Assurance", "Poison Fang")

Oricorio = Pokemon("Oricorio", None, "Flying", "Fire",
                   75, 98, 70, 93, "Air Slash",
                   "Revelation Dance", "Hurricane", "U-turn")

Overqwil = Pokemon("Overqwil", None, "Dark", "Poison",
                   85, 115, 95, 85, "Poison Jab",
                   "Crunch", "Aqua Jet", "Assurance")

Tauros_P_C = Pokemon("Paldean Tauros Combat", None, "Fighting", None,
                     75, 110, 105, 100, "Close Combat",
                     "Zen Headbutt", "Body Slam", "Wild Charge")

Tauros_P_B = Pokemon("Paldean Tauros Blaze", None, "Fighting", "Fire",
                     75, 110, 105, 100, "Close Combat",
                     "Flare Blitz", "Body Slam", "Wild Charge")

Tauros_P_A = Pokemon("Paldean Tauros Aqua", None, "Fighting", "Water",
                     75, 110, 105, 100, "Close Combat",
                     "Liquidation", "Body Slam", "Wild Charge")

Passimian = Pokemon("Passimian", None, "Fighting", None,
                    100, 120, 100, 80, "Close Combat",
                    "Rock Slide", "U-turn", "Earthquake")

Perrserker = Pokemon("Perrserker", None, "Steel", None,
                     70, 110, 100, 50, "Iron Head",
                     "Body Slam", "Assurance", "Metal Claw")

Porygon_Z = Pokemon("Porygon-Z", None, "Normal", None,
                    85, 135, 95, 90, "Tri Attack",
                    "Hyper Beam", "Psychic", "Shadow Ball")

Primarina = Pokemon("Primarina", None, "Water", "Fairy",
                    80, 126, 116, 60, "Hydro Pump",
                    "Moonblast", "Energy Ball", "Hyper Voice")

Pyroar = Pokemon("Pyroar", None, "Fire", "Normal",
                 86, 109, 90, 106, "Hyper Voice",
                 "Flamethrower", "Dark Pulse", "Hidden Power")

Quagsire = Pokemon("Quagsire", None, "Water", "Ground",
                   95, 85, 100, 35, "Earthquake",
                   "Waterfall", "Body Slam", "Ice Beam")

Rhyperior = Pokemon("Rhyperior", None, "Ground", "Rock",
                    115, 140, 130, 40, "Earthquake",
                    "Rock Wrecker", "Hammer Arm", "Megahorn")

Rotom = Pokemon("Rotom", None, "Electric", "Ghost",
                50, 95, 107, 91, "Thunderbolt",
                "Hex", "Volt Switch", "Dark Pulse")

Scrafty = Pokemon("Scrafty", None, "Dark", "Fighting",
                  65, 90, 115, 58, "Crunch",
                  "Brick Break", "Head Smash", "Assurance")

Sawsbuck = Pokemon("Sawsbuck", None, "Normal", "Grass",
                   80, 100, 95, 95, "Double-Edge",
                   "Horn Leech", "Body Slam", "Seed Bomb")

Sawk = Pokemon("Sawk", None, "Fighting", None,
               75, 125, 95, 85, "Close Combat",
               "Brick Break", "Poison Jab", "Ice Punch")

Skeledirge = Pokemon("Skeledirge", None, "Fire", "Ghost",
                     104, 110, 110, 66, "Shadow Ball",
                     "Flamethrower", "Hyper Voice", "Hex")

Slowbro = Pokemon("Slowbro", None, "Water", "Psychic",
                  95, 100, 110, 30, "Scald",
                  "Psyshock", "Ice Beam", "Body Slam")

Snorlax = Pokemon("Snorlax", None, "Normal", None,
                  160, 110, 110, 30, "Body Slam",
                  "Crunch", "Earthquake", "Ice Punch")

Spiritomb = Pokemon("Spiritomb", None, "Ghost", "Dark",
                    50, 92, 108, 35, "Dark Pulse",
                    "Hex", "Foul Play", "Assurance")

Staraptor = Pokemon("Staraptor", None, "Normal", "Flying",
                    85, 120, 80, 100, "Brave Bird",
                    "Close Combat", "Double-Edge", "U-turn")

Sneasler = Pokemon("Sneasler", None, "Fighting", "Poison",
                   80, 130, 80, 120, "Close Combat",
                   "Poison Jab", "Brick Break", "Night Slash")

Toxicroak = Pokemon("Toxicroak", None, "Poison", "Fighting",
                    83, 106, 90, 85, "Drain Punch",
                    "Gunk Shot", "Brick Break", "Sucker Punch")

Torterra = Pokemon("Torterra", None, "Grass", "Ground",
                   95, 109, 115, 56, "Earthquake",
                   "Seed Bomb", "Wood Hammer", "Body Slam")

Ursaluna = Pokemon("Ursaluna", None, "Ground", "Normal",
                   130, 140, 105, 50, "Earthquake",
                   "Facade", "Body Slam", "Headlong Rush")

Vileplume = Pokemon("Vileplume", None, "Grass", "Poison",
                    75, 110, 100, 50, "Sludge Wave",
                    "Energy Ball", "Giga Drain", "Petal Dance")

Vivillon = Pokemon("Vivillon", None, "Bug", "Flying",
                   80, 100, 75, 89, "Bug Buzz",
                   "Hurricane", "U-turn", "Energy Ball")

Whimsicott = Pokemon("Whimsicott", None, "Grass", "Fairy",
                     60, 95, 95, 116, "Energy Ball",
                     "Dazzling Gleam", "Giga Drain", "Moonblast")

Whiscash = Pokemon("Whiscash", None, "Water", "Ground",
                   110, 100, 90, 60, "Earthquake",
                   "Waterfall", "Stone Edge", "Body Slam")

Xatu = Pokemon("Xatu", None, "Psychic", "Flying",
               85, 95, 95, 95, "Psyshock",
               "Air Slash", "U-turn", "Dazzling Gleam")

Zoroark = Pokemon("Zoroark", None, "Dark", None,
                  60, 120, 80, 105, "Night Daze",
                  "Shadow Sneak", "Knock Off", "Dark Pulse")

Zoroark_H = Pokemon("Hisuian Zoroark", None, "Normal", "Ghost",
                    55, 125, 90, 110, "Hex",
                    "Shadow Sneak", "Body Slam", "Night Slash")

NU_Poke = [Metagross, Escavalier, Jolteon, Medicham, Mismagius, Clawitzer,
             Exeggutor_A, Avalugg_H, Blissey, Hariyama, Hoopa_U,
             Abomasnow, Ambipom, Amoonguss, Arcanine, Appletun, Avalugg,
             Azumarill, Banette, Barraskewda, Bellibolt, Bombirdier, Braviary, Braviary_H,
             Bruxish, Basculegion, Cacturne, Camerupt, Carbink, Chandelure,
             Crabominable, Decidueye, Decidueye_H, Drifblim, Dondozo, Espeon, Umbreon,
             Glaceon, Leafeon, Vaporeon, Electrode, Espathra, Feraligatr, Florges, Floatzel,
             Gardevoir, Gallade, Gyarados, Haxorus, Hatterene, Incineroar, Kilowattrel,
             Lanturn, Kommo_o, Krookodile, Lucario, Lurantis, Mabosstiff,
             Milotic, Magnezone, Manectric, Mimikyu, Muk, Muk_A, Oricorio,
             Overqwil, Tauros_P_C, Tauros_P_B, Tauros_P_A, Passimian, Perrserker,
             Porygon_Z, Primarina, Pyroar, Quagsire, Rhyperior, Rotom, Scrafty, Sawsbuck,
             Sawk, Skeledirge, Slowbro, Snorlax, Spiritomb, Staraptor, Sneasler, Toxicroak,
             Torterra, Ursaluna, Vileplume, Vivillon, Whimsicott, Whiscash, Xatu,
             Zoroark, Zoroark_H
             ]

# SV OU — non-legendary, final-evolution Pokémon
# Pokemon(name, None, type1, type2_or_None, HP, max(Atk,SpA), max(Def,SpD), Spe, move1, move2, move3, move4)

Charizard = Pokemon("Charizard", "Mega Charizard X",
                      "Fire", "Flying", 78, 109,
                      85, 100, "Overheat","Thunder Punch",
                    "Aerial Ace", "Shadow Claw")

Mega_Charizard_X = Pokemon("Mega Charizard X", "Charizard",
                            "Fire", "Dragon", 78,
                            130, 111, 100, "Overheat",
                           "Thunder Punch", "Shadow Claw",
                           "Dragon Claw")

Dialga_O = Pokemon("Dialga, Origin Form", None,
                            "Steel", "Dragon", 100,
                            150, 120, 90, "Roar of Time",
                   "Earthquake", "Hyper Beam", "Iron Tail")

Mega_Mewtwo_Y = Pokemon("Mega Mewtwo Y", None, "Psychic",
                        None, 106, 194, 120, 140,
                        "Psystrike", "Shadow Ball", "Hyper Beam",
                        "Ice Beam")

Landorus_T = Pokemon("Landorus Therian Form", None,
                           "Ground", "Flying", 89,
                           145, 90, 91, "Earthquake",
                           "Iron Tail", "Rock Slide", "Aerial Ace")

Torterra = Pokemon("Torterra", None, "Grass", "Ground",
                   95, 109, 105, 56, "Earthquake",
                   "Solar Beam", "Hyper Beam", "Rock Slide")

Blaziken = Pokemon("Blaziken", None, "Fire", "Fighting",
                   80, 120, 70, 80, "Blaze Kick",
                   "Aerial Ace", "Sky Uppercut", "Slash")

Mega_Blaziken = Pokemon("Mega Blaziken", None, "Fire", "Fighting",
                   80, 160, 80, 100, "Overheat",
                        "Sky Uppercut", "Thunder Punch", "Shadow Claw")

Rhyperior = Pokemon("Rhyperior", None, "Rock", "Ground",
                    115, 140, 55, 40, "Earthquake",
                    "Rock Slide", "Thunder Punch", "Ice Punch")

Cramorant = Pokemon("Cramorant", None, "Flying", "Water",
                    70, 85, 95, 85, "Hydropump",
                    "Aerial Ace", "Ice Beam", "Hyper Beam")

Vaporeon = Pokemon("Vaporeon", None, "Water", None,
                   130, 110, 95, 65, "Hydropump",
                   "Iron Tail", "Shadow Ball", "Ice Beam")

Raging_Bolt = Pokemon("Raging Bolt", None, "Electric",
                      "Dragon", 125, 137, 91, 75,
                      "Draco Meteor", "Thunderclap",
                      "Stomping Tantrum", "Crunch")

Ceruledge = Pokemon("Ceruledge", None, "Fire", "Ghost",
                    75, 125, 100, 85, "Close Combat",
                    "Phantom Force", "Flare Blitz", "Dragon Claw")

Giratina_O = Pokemon("Giratina Origin Form", None, "Ghost",
                     "Dragon", 150, 100, 120, 90,
                     "Phantom Force", "Outrage", "Aura Sphere",
                     "Thunder")

Sylveon = Pokemon("Sylveon", None, "Fairy", None,
                  95, 110, 130, 60, "Shadow Ball",
                  "Trump Card", "Moonblast", "Magical Leaf")

Venusaur = Pokemon("Venusaur", None, "Grass", "Poison",
                   80, 100, 100, 80, "Solar Beam",
                   "Sludge Bomb", "Stomping Tantrum", "Hyper Beam")

Blastoise = Pokemon("Blastoise", None, "Water", None,
                    79, 85, 105, 78, "Hydropump",
                    "Aura Sphere", "Seismic Toss", "Iron Tail")

Iron_Crown = Pokemon("Iron Crown", None, "Steel",
                     "Psychic", 90, 122, 108, 98,
                     "Hyper Beam", "Expanding Force",
                     "Flash Cannon", "Solar Blade")

Regice = Pokemon("Regice", None, "Ice", None, 80,
                 100, 200, 50, "Ice Beam", "Thunderbolt",
                 "Rock Tomb","Stomping Tantrum")

Lapras = Pokemon("Lapras", None, "Water", "Ice",
                 130, 85, 95, 60, "Ice Beam", "Surf",
                 "Iron Tail", "Psychic")

Glastrier = Pokemon("Glastrier", None, "Ice", None,
                    100, 145, 130, 30, "Close Combat",
                    "Ice Beam", "High Horsepower", "Crunch")

Vespiquen = Pokemon("Vespiquen", None, "Bug", "Flying",
                    70, 80, 102, 40, "X-Scissor",
                    "Sludge Bomb", "Aerial Ace", "Psychic Noise")

Mega_Scizor = Pokemon("Mega Scizor", None, "Bug",
                      "Steel", 70, 150, 140, 75,
                      "Bullet Punch", "X-Scissor", "Ominous Wind",
                      "Aerial Ace")

Arceus = Pokemon("Arceus", None, "Normal", None,
                 120, 120, 120, 120, "Judgment",
                 "Thunder", "Earthquake", "Seismic Toss")



Dragonite = Pokemon("Dragonite", None, "Dragon", "Flying",
                    91, 134, 100, 80, "Dragon Rush",
                    "Extreme Speed", "Earthquake", "Fire Blast")

Gholdengo = Pokemon("Gholdengo", None, "Steel", "Ghost",
                    87, 133, 95, 84, "Steel Beam",
                    "Hex", "Power Gem", "Dazzling Gleam")

Great_Tusk = Pokemon("Great Tusk", None, "Ground", "Fighting",
                     115, 131, 131, 87, "Earthquake",
                     "Body Press", "Stone Edge", "Brick Break")

Kingambit = Pokemon("Kingambit", None, "Dark", "Steel",
                    100, 135, 120, 50, "Knock Off",
                    "Iron Head", "Sucker Punch", "Stone Edge")

Gliscor = Pokemon("Gliscor", None, "Ground", "Flying",
                  75, 95, 125, 95, "Earthquake",
                  "U-turn", "Stone Edge", "Knock Off")

Dragapult = Pokemon("Dragapult", None, "Dragon", "Ghost",
                    88, 120, 75, 142, "Dragon Darts",
                    "Hex", "U-turn", "Fire Blast")

Garchomp = Pokemon("Garchomp", None, "Dragon", "Ground",
                   108, 130, 95, 102, "Earthquake",
                   "Dragon Rush", "Stone Edge", "Fire Fang")

Gouging_Fire = Pokemon("Gouging Fire", None, "Fire", "Dragon",
                       105, 115, 121, 91, "Fire Fang",
                       "Dragon Rush", "Stone Edge", "Earthquake")

Roaring_Moon = Pokemon("Roaring Moon", None, "Dark", "Dragon",
                       105, 139, 101, 119, "Night Slash",
                       "Dragon Rush", "Earthquake", "U-turn")

Slowking_G = Pokemon("Galarian Slowking", None, "Poison", "Psychic",
                     95, 110, 110, 30, "Sludge Wave",
                     "Psyshock", "Scald", "Fire Blast")

Archaludon = Pokemon("Archaludon", None, "Steel", "Dragon",
                     90, 125, 130, 85, "Steel Beam",
                     "Dragon Pulse", "Thunder Shock", "Flash Cannon")

Hatterene = Pokemon("Hatterene", None, "Psychic", "Fairy",
                    57, 136, 103, 29, "Dazzling Gleam",
                    "Psyshock", "Mystical Fire", "Draining Kiss")

Iron_Valiant = Pokemon("Iron Valiant", None, "Fairy", "Fighting",
                       74, 130, 90, 116, "Play Rough",
                       "Sacred Sword", "Psycho Cut", "Brick Break")

Pelipper = Pokemon("Pelipper", None, "Water", "Flying",
                   60, 95, 100, 65, "Scald",
                   "Hurricane", "U-turn", "Hydro Pump")

Samurott_H = Pokemon("Hisuian Samurott", None, "Water", "Dark",
                     90, 108, 80, 85, "Razor Shell",
                     "Aqua Jet", "Night Slash", "Megahorn")

Skarmory = Pokemon("Skarmory", None, "Steel", "Flying",
                   65, 80, 140, 70, "Brave Bird",
                   "Steel Wing", "Body Press", "Rock Blast")


Glimmora = Pokemon("Glimmora", None, "Rock", "Poison",
                   83, 130, 90, 86, "Power Gem",
                   "Sludge Wave", "Ancient Power", "Energy Ball")

Dondozo = Pokemon("Dondozo", None, "Water", None,
                  150, 100, 115, 35, "Waterfall",
                  "Body Press", "Earthquake", "Body Slam")

Excadrill = Pokemon("Excadrill", None, "Ground", "Steel",
                    110, 135, 65, 88, "Earthquake",
                    "Iron Head", "Rock Slide", "Brick Break")

Iron_Hands = Pokemon("Iron Hands", None, "Fighting", "Electric",
                     154, 140, 108, 50, "Drain Punch",
                     "Wild Charge", "Thunder Punch", "Brick Break")

Toxapex = Pokemon("Toxapex", None, "Poison", "Water",
                  50, 63, 152, 35, "Scald",
                  "Sludge Wave", "Poison Jab", "Brine")

Tyranitar = Pokemon("Tyranitar", None, "Rock", "Dark",
                    100, 134, 110, 61, "Stone Edge",
                    "Crunch", "Earthquake", "Fire Fang")


Clodsire = Pokemon("Clodsire", None, "Poison", "Ground",
                   130, 75, 100, 20, "Earthquake",
                   "Poison Jab", "Mud Shot", "Body Slam")

Greninja = Pokemon("Greninja", None, "Water", "Dark",
                   72, 103, 71, 122, "Hydro Pump",
                   "Dark Pulse", "U-turn", "Ice Beam")

Hydrapple = Pokemon("Hydrapple", None, "Grass", "Dragon",
                    106, 120, 110, 44, "Energy Ball",
                    "Dragon Pulse", "Giga Drain", "Ancient Power")

Weezing_G = Pokemon("Galarian Weezing", None, "Poison", "Fairy",
                    65, 90, 120, 60, "Strange Steam",
                    "Sludge Wave", "Play Rough", "Dazzling Gleam")

Cinderace = Pokemon("Cinderace", None, "Fire", None,
                    80, 116, 75, 119, "Pyro Ball",
                    "U-turn", "High Jump Kick", "Sucker Punch")

Corviknight = Pokemon("Corviknight", None, "Flying", "Steel",
                      98, 87, 105, 67, "Brave Bird",
                      "Body Press", "Steel Wing", "U-turn")

Garganacl = Pokemon("Garganacl", None, "Rock", None,
                    100, 100, 130, 35, "Rock Blast",
                    "Smack Down", "Body Press", "Rock Throw")

Iron_Treads = Pokemon("Iron Treads", None, "Ground", "Steel",
                      90, 112, 120, 106, "Earthquake",
                      "Iron Head", "Stone Edge", "Rapid Spin")

Rillaboom = Pokemon("Rillaboom", None, "Grass", None,
                    100, 125, 90, 85, "Grassy Glide",
                    "Wood Hammer", "Knock Off", "U-turn")

Meowscarada = Pokemon("Meowscarada", None, "Grass", "Dark",
                      76, 110, 70, 123, "Knock Off",
                      "U-turn", "Play Rough", "Leaf Blade")

Serperior = Pokemon("Serperior", None, "Grass", None,
                    75, 75, 95, 113, "Leaf Blade",
                    "Energy Ball", "Dragon Pulse", "Giga Drain")

Alomomola = Pokemon("Alomomola", None, "Water", None,
                    165, 75, 80, 65, "Waterfall",
                    "Aqua Jet", "Bounce", "Body Slam")

Torkoal = Pokemon("Torkoal", None, "Fire", None,
                  70, 85, 140, 20, "Lava Plume",
                  "Eruption", "Heat Wave", "Body Slam")

Rotom_W = Pokemon("Rotom-Wash", None, "Electric", "Water",
                  50, 105, 107, 86, "Hydro Pump",
                  "Volt Switch", "Discharge", "Hex")

Scizor = Pokemon("Scizor", None, "Bug", "Steel",
                 70, 130, 100, 65, "Metal Claw",
                 "Bug Bite", "Brick Break", "Knock Off")

Weavile = Pokemon("Weavile", None, "Dark", "Ice",
                  70, 120, 85, 125, "Night Slash",
                  "Icicle Crash", "Ice Shard", "Knock Off")

Hawlucha = Pokemon("Hawlucha", None, "Fighting", "Flying",
                   78, 92, 75, 118, "High Jump Kick",
                   "Brave Bird", "Flying Press", "Poison Jab")

Primarina = Pokemon("Primarina", None, "Water", "Fairy",
                    80, 126, 116, 60, "Hydro Pump",
                    "Dazzling Gleam", "Energy Ball", "Hyper Voice")

Ninetales_A = Pokemon("Alolan Ninetales", None, "Ice", "Fairy",
                      73, 81, 100, 109, "Blizzard",
                      "Dazzling Gleam", "Aurora Beam", "Ice Shard")

Iron_Moth = Pokemon("Iron Moth", None, "Fire", "Poison",
                    80, 140, 90, 110, "Fiery Dance",
                    "Sludge Wave", "Energy Ball", "Dazzling Gleam")

Iron_Boulder = Pokemon("Iron Boulder", None, "Rock", "Psychic",
                       90, 120, 80, 124, "Stone Edge",
                       "Psycho Cut", "Brick Break", "Night Slash")

Iron_Bundle = Pokemon("Iron Bundle", None, "Ice", "Water",
                      56, 124, 114, 136, "Freeze-Dry",
                      "Hydro Pump", "Ice Beam", "Flip Turn")

Walking_Wake = Pokemon("Walking Wake", None, "Water", "Dragon",
                       99, 125, 91, 109, "Hydro Pump",
                       "Dragon Pulse", "Scald", "Flip Turn")

Quaquaval = Pokemon("Quaquaval", None, "Water", "Fighting",
                    85, 120, 85, 85, "Aqua Jet",
                    "Waterfall", "Brick Break", "Ice Spinner")

Hydreigon = Pokemon("Hydreigon", None, "Dark", "Dragon",
                    92, 125, 90, 98, "Dark Pulse",
                    "Dragon Pulse", "Flash Cannon", "Fire Blast")

Lokix = Pokemon("Lokix", None, "Bug", "Dark",
                71, 102, 78, 92, "First Impression",
                "U-turn", "Thief", "Lunge")

Mamoswine = Pokemon("Mamoswine", None, "Ice", "Ground",
                    110, 130, 80, 80, "Icicle Crash",
                    "Earthquake", "Ice Shard", "Stone Edge")

Azumarill = Pokemon("Azumarill", None, "Water", "Fairy",
                    100, 60, 80, 50, "Aqua Jet",
                    "Play Rough", "Waterfall", "Superpower")

Toxtricity = Pokemon("Toxtricity", None, "Electric", "Poison",
                     75, 114, 91, 75, "Overdrive",
                     "Discharge", "Sludge Wave", "Boomburst")

Hisuian_Zoroark = Pokemon("Hisuian Zoroark", None, "Normal", "Ghost",
                          55, 125, 90, 110, "Hex",
                          "Shadow Sneak", "Body Slam", "Night Slash")

Zoroark = Pokemon("Zoroark", None, "Dark", None,
                  60, 120, 80, 105, "Night Daze",
                  "Knock Off", "Shadow Sneak", "Dark Pulse")

Gyarados = Pokemon("Gyarados", None, "Water", "Flying",
                   95, 125, 100, 81, "Waterfall",
                   "Bounce", "Stone Edge", "Earthquake")

Alolan_Muk = Pokemon("Alolan Muk", None, "Poison", "Dark",
                     105, 105, 100, 50, "Gunk Shot",
                     "Crunch", "Poison Fang", "Assurance")

Baxcalibur = Pokemon("Baxcalibur", None, "Dragon", "Ice",
                     115, 145, 92, 87, "Icicle Crash",
                     "Dragon Rush", "Earthquake", "Ice Shard")

Breloom = Pokemon("Breloom", None, "Grass", "Fighting",
                  60, 130, 80, 70, "Mach Punch",
                  "Seed Bomb", "Bullet Seed", "Rock Tomb")

Scovillain = Pokemon("Scovillain", None, "Grass", "Fire",
                     65, 108, 75, 75, "Energy Ball",
                     "Flamethrower", "Leaf Storm", "Heat Wave")

Maushold = Pokemon("Maushold", None, "Normal", None,
                   74, 75, 77, 111, "Facade",
                   "U-turn", "Bite", "Hyper Voice")

Hippowdon = Pokemon("Hippowdon", None, "Ground", None,
                    108, 112, 118, 47, "Earthquake",
                    "Body Slam", "Rock Slide", "Crunch")


OU_Poke = [
    Dragonite, Gholdengo, Great_Tusk, Kingambit, Gliscor, Dragapult, Garchomp,
    Gouging_Fire, Raging_Bolt, Roaring_Moon, Slowking_G, Archaludon, Hatterene,
    Iron_Valiant, Pelipper, Samurott_H, Skarmory, Ceruledge, Glimmora, Dondozo,
    Excadrill, Iron_Hands, Toxapex, Tyranitar, Venusaur, Blaziken, Clodsire,
    Greninja, Hydrapple, Weezing_G, Cinderace, Corviknight, Garganacl,
    Iron_Treads, Rillaboom, Meowscarada, Serperior, Alomomola, Torkoal,
    Rotom_W, Scizor, Weavile, Hawlucha, Primarina, Ninetales_A, Iron_Moth,
    Iron_Boulder, Iron_Bundle, Walking_Wake, Gyarados, Alolan_Muk, Baxcalibur,
    Breloom, Scovillain, Maushold, Hippowdon, Hisuian_Zoroark, Zoroark,
    Charizard, Mega_Charizard_X, Dialga_O, Mega_Mewtwo_Y, Landorus_T,
    Torterra, Blaziken, Mega_Blaziken, Rhyperior, Cramorant, Vaporeon,
    Ceruledge, Giratina_O, Sylveon, Venusaur, Blastoise, Iron_Crown,
    Regice, Lapras, Glastrier, Vespiquen, Mega_Scizor

]

# UBERS — Legendaries/Mythicals (one non-base form where applicable) + ALL allowed Megas (minus your excluded ones)
# Pokemon(name, None, type1, type2_or_None, HP, max(Atk,SpA), max(Def,SpD), Spe, move1, move2, move3, move4)

# --- Main Uber Legendaries / Mythicals (SV-era relevant) ---

Mewtwo_MX = Pokemon("Mega Mewtwo X", None, "Psychic", "Fighting",
                    106, 190, 100, 130, "Psyshock",
                    "Focus Blast", "Brick Break", "Zen Headbutt")

Rayquaza_M = Pokemon("Mega Rayquaza", None, "Dragon", "Flying",
                     105, 180, 115, 115, "Dragon Ascent",
                     "V-Create", "Extreme Speed", "Dragon Rush")

Kyogre_P = Pokemon("Primal Kyogre", None, "Water", None,
                   100, 180, 160, 90, "Origin Pulse",
                   "Hydro Pump", "Water Spout", "Blizzard")

Groudon_P = Pokemon("Primal Groudon", None, "Ground", "Fire",
                    100, 180, 160, 90, "Precipice Blades",
                    "Fire Blast", "Lava Plume", "Stone Edge")

Palkia_O = Pokemon("Palkia-Origin", None, "Water", "Dragon",
                   90, 150, 120, 120, "Hydro Pump",
                   "Dragon Pulse", "Aqua Tail", "Ancient Power")

Kyurem_W = Pokemon("Kyurem-White", None, "Dragon", "Ice",
                   125, 170, 100, 95, "Ice Burn",
                   "Fusion Flare", "Dragon Pulse", "Blizzard")

Xerneas = Pokemon("Xerneas", None, "Fairy", None,
                  126, 131, 98, 99, "Dazzling Gleam",
                  "Draining Kiss", "Energy Ball", "Psychic")

Yveltal = Pokemon("Yveltal", None, "Dark", "Flying",
                  126, 131, 98, 99, "Dark Pulse",
                  "Oblivion Wing", "Hurricane", "Sucker Punch")

Zygarde_C = Pokemon("Zygarde-Complete", None, "Dragon", "Ground",
                    216, 100, 121, 85, "Thousand Arrows",
                    "Thousand Waves", "Dragon Tail", "Crunch")

Solgaleo = Pokemon("Solgaleo", None, "Psychic", "Steel",
                   137, 137, 107, 97, "Iron Head",
                   "Zen Headbutt", "Brick Break", "Fire Blast")

Lunala = Pokemon("Lunala", None, "Ghost", "Psychic",
                 137, 137, 107, 97, "Moongeist Beam",
                 "Psychic", "Hex", "Air Slash")

Necrozma_U = Pokemon("Ultra Necrozma", None, "Psychic", "Dragon",
                     97, 167, 97, 129, "Photon Geyser",
                     "Prismatic Laser", "Dragon Pulse", "Psyshock")

Zacian_C = Pokemon("Zacian-Crowned", None, "Fairy", "Steel",
                   92, 170, 115, 148, "Play Rough",
                   "Iron Head", "Sacred Sword", "Wild Charge")

Zamazenta_C = Pokemon("Zamazenta-Crowned", None, "Fighting", "Steel",
                      92, 130, 145, 128, "Brick Break",
                      "Iron Head", "Crunch", "Body Slam")

Eternatus = Pokemon("Eternatus", None, "Poison", "Dragon",
                    140, 145, 95, 130, "Dynamax Cannon",
                    "Sludge Wave", "Dragon Pulse", "Fire Blast")

Koraidon = Pokemon("Koraidon", None, "Fighting", "Dragon",
                   100, 135, 115, 135, "Brick Break",
                   "Dragon Rush", "Fire Fang", "Crunch")

Miraidon = Pokemon("Miraidon", None, "Electric", "Dragon",
                   100, 135, 100, 135, "Discharge",
                   "Volt Switch", "Dragon Pulse", "Overdrive")

Calyrex_S = Pokemon("Calyrex-Shadow", None, "Psychic", "Ghost",
                    100, 165, 100, 150, "Hex",
                    "Psyshock", "Energy Ball", "Shadow Sneak")

Reshiram = Pokemon("Reshiram", None, "Dragon", "Fire",
                   100, 150, 120, 90, "Fusion Flare",
                   "Dragon Pulse", "Heat Wave", "Extrasensory")

Zekrom = Pokemon("Zekrom", None, "Dragon", "Electric",
                 100, 150, 120, 90, "Fusion Bolt",
                 "Dragon Rush", "Wild Charge", "Crunch")

HoOh = Pokemon("Ho-Oh", None, "Fire", "Flying",
               106, 130, 154, 90, "Sacred Fire",
               "Brave Bird", "Lava Plume", "Ancient Power")

Lugia = Pokemon("Lugia", None, "Psychic", "Flying",
                106, 90, 154, 110, "Air Slash",
                "Hurricane", "Psychic", "Dragon Tail")

Genesect = Pokemon("Genesect", None, "Bug", "Steel",
                   71, 120, 95, 99, "Techno Blast",
                   "Iron Head", "U-turn", "Bug Buzz")

Darkrai = Pokemon("Darkrai", None, "Dark", None,
                  70, 135, 90, 125, "Dark Pulse",
                  "Snarl", "Hex", "Knock Off")

Deoxys_A = Pokemon("Deoxys-Attack", None, "Psychic", None,
                   50, 180, 20, 150, "Psycho Boost",
                   "Brick Break", "Dark Pulse", "Knock Off")

Shaymin_S = Pokemon("Shaymin-Sky", None, "Grass", "Flying",
                    100, 120, 75, 127, "Seed Flare",
                    "Air Slash", "Energy Ball", "Extrasensory")

Victini = Pokemon("Victini", None, "Psychic", "Fire",
                  100, 100, 100, 100, "V-Create",
                  "Zen Headbutt", "Flame Charge", "Psychic")

Volcanion = Pokemon("Volcanion", None, "Fire", "Water",
                    80, 130, 120, 70, "Steam Eruption",
                    "Heat Wave", "Scorching Sands", "Sludge Wave")

Zeraora = Pokemon("Zeraora", None, "Electric", None,
                  88, 112, 80, 143, "Plasma Fists",
                  "Wild Charge", "Brick Break", "Knock Off")

Marshadow = Pokemon("Marshadow", None, "Fighting", "Ghost",
                    90, 125, 90, 125, "Shadow Sneak",
                    "Drain Punch", "Brick Break", "Night Slash")

Regigigas = Pokemon("Regigigas", None, "Normal", None,
                    110, 160, 110, 100, "Crush Claw",
                    "Body Slam", "Rock Slide", "Brick Break")

Mew = Pokemon("Mew", None, "Psychic", None,
              100, 100, 100, 100, "Psychic",
              "Tri Attack", "Aura Sphere", "Scald")

Magearna = Pokemon("Magearna", None, "Steel", "Fairy",
                   80, 130, 115, 65, "Fleur Cannon",
                   "Flash Cannon", "Dazzling Gleam", "Energy Ball")

ChiYu = Pokemon("Chi-Yu", None, "Dark", "Fire",
                55, 135, 120, 100, "Dark Pulse",
                "Fiery Dance", "Burning Jealousy", "Lava Plume")

ChienPao = Pokemon("Chien-Pao", None, "Dark", "Ice",
                   80, 120, 80, 135, "Night Slash",
                   "Icicle Crash", "Ice Shard", "Crunch")

TingLu = Pokemon("Ting-Lu", None, "Dark", "Ground",
                 155, 110, 125, 45, "Earth Power",
                 "Rock Slide", "Payback", "Body Slam")

WoChien = Pokemon("Wo-Chien", None, "Dark", "Grass",
                  85, 95, 135, 70, "Giga Drain",
                  "Energy Ball", "Dark Pulse", "Leaf Blade")

Keldeo_R = Pokemon("Keldeo-Resolute", None, "Water", "Fighting",
                   91, 129, 90, 108, "Scald",
                   "Hydro Pump", "Secret Sword", "Brick Break")

# --- Mega Evolutions (ALL allowed; excluding your explicitly banned ones) ---

Mega_Charizard_Y = Pokemon("Mega Charizard Y", None, "Fire", "Flying",
                           78, 159, 115, 100, "Fire Blast",
                           "Air Slash", "Ancient Power", "Dragon Pulse")

Mega_Garchomp = Pokemon("Mega Garchomp", None, "Dragon", "Ground",
                        108, 170, 115, 92, "Outrage",
                        "Stone Edge", "Overheat", "Earthquake")

Mega_Salamence = Pokemon("Mega Salamence", None, "Dragon", "Flying",
                         95, 145, 130, 120, "Outrage",
                         "Fly", "Stone Edge", "Earthquake")

Mega_Metagross = Pokemon("Mega Metagross", None, "Steel", "Psychic",
                         80, 145, 150, 110, "Meteor Mash",
                         "Zen Headbutt", "Dynamic Punch", "Rock Slide")

Mega_Mawile = Pokemon("Mega Mawile", None, "Steel", "Fairy",
                      50, 105, 125, 50, "Play Rough",
                      "Iron Head", "Sucker Punch", "Focus Punch")

Mega_Medicham = Pokemon("Mega Medicham", None, "Fighting", "Psychic",
                        60, 100, 85, 100, "High Jump Kick",
                        "Zen Headbutt", "Drain Punch", "Shadow Ball")

Mega_Lopunny = Pokemon("Mega Lopunny", None, "Normal", "Fighting",
                       65, 136, 96, 135, "High Jump Kick",
                       "Double-Edge", "Ice Punch", "Thunder Punch")

Mega_Kangaskhan = Pokemon("Mega Kangaskhan", None, "Normal", None,
                          105, 125, 100, 100, "Double-Edge",
                          "Crunch", "Brick Break", "Rock Slide")

Mega_Gyarados = Pokemon("Mega Gyarados", None, "Water", "Dark",
                        95, 155, 130, 81, "Waterfall",
                        "Crunch", "Dragon Tail", "Ice Fang")

Mega_Diancie = Pokemon("Mega Diancie", None, "Rock", "Fairy",
                       50, 160, 110, 110, "Diamond Storm",
                       "Dark Pulse", "Dazzling Gleam", "Ancient Power")

Mega_Gallade = Pokemon("Mega Gallade", None, "Psychic", "Fighting",
                       68, 165, 115, 110, "Psycho Cut",
                       "Close Combat", "Magical Leaf", "Night Slash")

Mega_Gardevoir = Pokemon("Mega Gardevoir", None, "Psychic", "Fairy",
                         68, 165, 135, 100, "Dazzling Gleam",
                         "Shadow Ball", "Hyper Voice", "Mystical Fire")

Mega_Alakazam = Pokemon("Mega Alakazam", None, "Psychic", None,
                        55, 175, 95, 150, "Psychic",
                        "Shadow Ball", "Dazzling Gleam", "Energy Ball")

Mega_Aerodactyl = Pokemon("Mega Aerodactyl", None, "Rock", "Flying",
                          80, 135, 95, 150, "Stone Edge",
                          "Air Slash", "Crunch", "Ice Fang")

Mega_Manectric = Pokemon("Mega Manectric", None, "Electric", None,
                         70, 135, 80, 135, "Discharge",
                         "Volt Switch", "Overdrive", "Thunder Fang")

Mega_Sharpedo = Pokemon("Mega Sharpedo", None, "Water", "Dark",
                        70, 140, 70, 105, "Crunch",
                        "Liquidation", "Aqua Jet", "Ice Fang")

Mega_Camerupt = Pokemon("Mega Camerupt", None, "Fire", "Ground",
                        70, 145, 105, 20, "Eruption",
                        "Lava Plume", "Earth Power", "Ancient Power")

Mega_Altaria = Pokemon("Mega Altaria", None, "Dragon", "Fairy",
                       75, 110, 110, 80, "Dragon Pulse",
                       "Dazzling Gleam", "Facade", "Fire Blast")

Mega_Banette = Pokemon("Mega Banette", None, "Ghost", None,
                       64, 165, 83, 75, "Shadow Punch",
                       "Gunk Shot", "Dazzling Gleam", "Foul Play")

Mega_Absol = Pokemon("Mega Absol", None, "Dark", None,
                     65, 150, 60, 115, "Night Slash",
                     "Sucker Punch", "Psycho Cut", "Play Rough")

Mega_Sableye = Pokemon("Mega Sableye", None, "Dark", "Ghost",
                       50, 85, 125, 20, "Foul Play",
                       "Shadow Sneak", "Hex", "Dark Pulse")

Mega_Aggron = Pokemon("Mega Aggron", None, "Steel", None,
                      70, 140, 230, 50, "Iron Head",
                      "Rock Slide", "Body Press", "Smack Down")

Mega_Beedrill = Pokemon("Mega Beedrill", None, "Bug", "Poison",
                        65, 150, 80, 145, "U-turn",
                        "Poison Jab", "Fell Stinger", "Bug Bite")

Mega_Pinsir = Pokemon("Mega Pinsir", None, "Bug", "Flying",
                      65, 155, 120, 105, "Brave Bird",
                      "Lunge", "Quick Attack", "Stone Edge")

Mega_Heracross = Pokemon("Mega Heracross", None, "Bug", "Fighting",
                         80, 185, 115, 75, "Megahorn",
                         "Brick Break", "Bullet Seed", "Rock Blast")

Mega_Houndoom = Pokemon("Mega Houndoom", None, "Dark", "Fire",
                        75, 140, 90, 115, "Dark Pulse",
                        "Fire Blast", "Incinerate", "Burning Jealousy")

Mega_Tyranitar = Pokemon("Mega Tyranitar", None, "Rock", "Dark",
                         100, 164, 150, 71, "Stone Edge",
                         "Crunch", "Fire Fang", "Earthquake")

Mega_Pidgeot = Pokemon("Mega Pidgeot", None, "Normal", "Flying",
                       83, 135, 80, 121, "Hurricane",
                       "Air Slash", "Heat Wave", "U-turn")

Mega_Latios = Pokemon("Mega Latios", None, "Dragon", "Psychic",
                      80, 160, 120, 110, "Dragon Pulse",
                      "Psyshock", "Hydro Pump", "Energy Ball")

Mega_Latias = Pokemon("Mega Latias", None, "Dragon", "Psychic",
                      80, 140, 150, 110, "Dragon Pulse",
                      "Psyshock", "Dazzling Gleam", "Hydro Pump")

Mega_Steelix = Pokemon("Mega Steelix", None, "Steel", "Ground",
                       75, 125, 230, 30, "Iron Head",
                       "Rock Slide", "Earthquake", "Smack Down")

Mega_Swampert = Pokemon("Mega Swampert", None, "Water", "Ground",
                        100, 150, 110, 70, "Hydro Cannon",
                        "Earthquake", "Ice Fang", "Focus Punch")

Mega_Sceptile = Pokemon("Mega Sceptile", None, "Grass", "Dragon",
                        70, 145, 85, 145, "Focus Punch",
                        "Leaf Storm", "Outrage", "X-Scissor")

Mega_Ampharos = Pokemon("Mega Ampharos", None, "Electric", "Dragon",
                        90, 165, 110, 45, "Thunder",
                        "Volt Switch", "Dragon Pulse", "Stone Edge")

Mega_Abomasnow = Pokemon("Mega Abomasnow", None, "Grass", "Ice",
                         90, 132, 105, 30, "Blizzard",
                         "Giga Impact", "Ice Shard", "Solar Beam")

Mega_Gengar = Pokemon("Mega Gengar", None, "Ghost", "Poison",
                      60, 170, 95, 130, "Hyper Beam",
                      "Dark Pulse", "Sludge Bomb", "Dazzling Gleam")

Mega_Glalie = Pokemon("Mega Glalie", None, "Ice", None,
                      80, 120, 80, 100, "Freeze-Dry",
                      "Ice Fang", "Hyper Beam", "Crunch")

Mega_Slowbro = Pokemon("Mega Slowbro", None, "Water", "Psychic",
                       95, 130, 180, 30, "Scald",
                       "Psyshock", "Icy Wind", "Hyper Beam")

Mega_Lucario = Pokemon("Mega Lucario", None, "Fighting", "Steel",
                       70, 145, 88, 112, "Close Combat",
                       "Bone Rush", "Flash Cannon", "Extreme Speed")


# ----------------------------
# Ubers_Poke master list
# ----------------------------
Uber_Poke = [
    # Uber legendaries & mythicals
    Mewtwo_MX, Rayquaza_M, Kyogre_P, Groudon_P, Palkia_O, Kyurem_W, Xerneas, Yveltal,
    Zygarde_C, Solgaleo, Lunala, Necrozma_U, Zacian_C, Zamazenta_C, Eternatus, Koraidon,
    Miraidon, Calyrex_S, Reshiram, Zekrom, HoOh, Lugia, Genesect, Darkrai, Deoxys_A,
    Shaymin_S, Victini, Volcanion, Zeraora, Marshadow, Regigigas, Mew, Magearna,
    ChiYu, ChienPao, TingLu, WoChien, Keldeo_R,
    Mega_Charizard_Y, Mega_Garchomp, Mega_Salamence, Mega_Metagross, Mega_Mawile,
    Mega_Medicham, Mega_Lopunny, Mega_Kangaskhan, Mega_Gyarados, Mega_Diancie,
    Mega_Gallade, Mega_Gardevoir, Mega_Alakazam, Mega_Aerodactyl, Mega_Manectric,
    Mega_Sharpedo, Mega_Camerupt, Mega_Altaria, Mega_Banette, Mega_Absol, Mega_Sableye,
    Mega_Aggron, Mega_Beedrill, Mega_Pinsir, Mega_Heracross, Mega_Houndoom,
    Mega_Tyranitar, Mega_Pidgeot, Mega_Latios, Mega_Latias, Mega_Steelix, Mega_Swampert,
    Mega_Sceptile, Mega_Ampharos, Mega_Abomasnow, Mega_Gengar, Mega_Glalie, Mega_Slowbro,
    Mega_Lucario
]















# print(len(LC_Poke))
# print(len(OU_Poke))
# print(len(NU_Poke))
# print(len(Uber_Poke))
# print(57 + 80 + 96 + 77)
#
# for pokemon in LC_Poke:  # THIS CODE IS FOR TESTING GENERATED POKEMON ATTACKS ARE IN THE ATTACK DICT
#         if pokemon.atk_1 not in attack_dict:
#             print(str(pokemon.atk_1))
#         if pokemon.atk_2 not in attack_dict:
#             print(str(pokemon.atk_2))
#         if pokemon.atk_3 not in attack_dict:
#             print(str(pokemon.atk_3))
#         if pokemon.atk_4 not in attack_dict:
#             print(str(pokemon.atk_4))