import random

attack_dict = {
    "DELETE": ("Dark", 9999),
    "Judgment": ("All", 9999),
    "Seismic Toss": ("Fighting", 95),
    "Thunder": ("Electric", 110),
    "Thunderclap": ("Electric", 110),
    "Crunch": ("Dark", 80),
    "Stomping Tantrum": ("Ground", 75),
    "Magical Leaf": ("Grass", 80),
    "Air Slash": ("Flying", 80),
    "Flamethrower": ("Fire", 95),
    "Dragon Claw": ("Dragon", 80),
    "Hydropump": ("Water", 120),
    "Draco Meteor": ("Dragon", 130),
    "Moonblast": ("Fairy", 95),
    "Bitter Blade": ("Fire", 90),
    "Close Combat": ("Fighting", 120),
    "Phantom Force": ("Ghost", 90),
    "Outrage": ("Dragon", 120),
    "Aura Sphere": ("Fighting", 80),
    "Trump Card": ("Normal", random.randint(50, 175)),
    "Ominous Wind": ("Ghost", 75),
    "Sludge Bomb": ("Poison", 90),
    "Solar Blade": ("Grass", 125),
    "X-Scissor": ("Bug", 80),
    "Psychic Noise": ("Psychic", 75),
    "Expanding Force": ("Psychic", 80),
    "Bullet Punch": ("Steel", 95),
    "Flash Cannon": ("Steel", 80),
    "Hyperspace Fury": ("Dark", 120),
    "Future Sight": ("Psychic", 120),
    "Earthquake": ("Ground", 100),
    "Roar of Time": ("Dragon", 150),
    "Shadow Ball": ("Ghost", 80),
    "Psystrike": ("Psychic", 100),
    "Blaze Kick": ("Fire", 85),
    "Sky Uppercut": ("Fighting", 85),
    "Focus Punch": ("Fighting", 150),
    "Stone Edge": ("Rock", 85),
    "Iron Head": ("Steel", 80),
    "Drill Run": ("Ground", 80),
    "Thunderbolt": ("Electric", 90),
    "Ice Beam": ("Ice", 95),
    "Mountain Gale": ("Ice", 100),
    "Dig": ("Ground", 80),
    "Double Edge": ("Normal", 120),
    "Rock Slide": ("Rock", 75),
    "Scratch": ("Normal", 40),
    "Aerial Ace": ("Flying", 90),
    "Thunder Punch": ("Electric", 75),
    "Fire Punch": ("Fire", 75),
    "Psychic": ("Psychic", 90),
    "Poison Jab": ("Poison", 80),
    "Surf": ("Water", 90),
    "Ice Punch": ("Ice", 75),
    "Leaf Storm": ("Grass", 130),
    "Flare Blitz": ("Fire", 120),
    "High Horsepower": ("Ground", 95),
    "Overheat": ("Fire", 130),
    "Solar Beam": ("Grass", 120),
    "Shadow Claw": ("Ghost", 70),
    "Rock Tomb": ("Rock", 70),
    "Hyper Beam": ("Normal", 150),
    "Giga Impact": ("Normal", 150),
    "Iron Tail": ("Steel", 100),
    "Slash": ("Normal", 70),
    "Headlong Rush": ("Ground", 120),
    "Gyro Ball": ("Steel", 60),
    "Acid Spray": ("Poison", 60),
    "Explosion": ("Noraml", 200),
    "Anchor Shot": ("Steel", 80), #Everything from here onwards was written by chat gpt
    "Ancient Power": ("Rock", 60),
    "Aqua Jet": ("Water", 40),
    "Aqua Tail": ("Water", 90),
    "Arm Thrust": ("Fighting", 15),
    "Assurance": ("Dark", 60),
    "Astonish": ("Ghost", 30),
    "Attack Order": ("Bug", 90),
    "Aura Wheel": ("Electric", 110),
    "Aurora Beam": ("Ice", 65),
    "Avalanche": ("Ice", 60),
    "Beak Blast": ("Flying", 100),
    "Bite": ("Dark", 60),
    "Blast Burn": ("Fire", 150),
    "Blizzard": ("Ice", 110),
    "Blue Flare": ("Fire", 130),
    "Body Press": ("Fighting", 80),
    "Body Slam": ("Normal", 85),
    "Bolt Strike": ("Electric", 130),
    "Bolt Beak": ("Electric", 85),
    "Bone Club": ("Ground", 65),
    "Bone Rush": ("Ground", 25),
    "Bonemerang": ("Ground", 50),
    "Boomburst": ("Normal", 140),
    "Bounce": ("Flying", 85),
    "Brave Bird": ("Flying", 120),
    "Branch Poke": ("Grass", 40),
    "Breaking Swipe": ("Dragon", 60),
    "Brick Break": ("Fighting", 75),
    "Brine": ("Water", 65),
    "Brutal Swing": ("Dark", 60),
    "Bubble": ("Water", 40),
    "Bubble Beam": ("Water", 65),
    "Bug Bite": ("Bug", 60),
    "Bug Buzz": ("Bug", 90),
    "Bulldoze": ("Ground", 60),
    "Bullet Seed": ("Grass", 25),
    "Burn Up": ("Fire", 130),
    "Burning Jealousy": ("Fire", 70),
    "Charge Beam": ("Electric", 50),
    "Chatter": ("Flying", 65),
    "Chip Away": ("Normal", 70),
    "Clamp": ("Water", 35),
    "Clear Smog": ("Poison", 50),
    "Comet Punch": ("Normal", 18),
    "Confusion": ("Psychic", 50),
    "Constrict": ("Normal", 10),
    "Core Enforcer": ("Dragon", 100),
    "Crabhammer": ("Water", 100),
    "Cross Chop": ("Fighting", 100),
    "Cross Poison": ("Poison", 70),
    "Crush Claw": ("Normal", 75),
    "Cut": ("Normal", 50),
    "Dark Pulse": ("Dark", 80),
    "Darkest Lariat": ("Dark", 85),
    "Dazzling Gleam": ("Fairy", 80),
    "Diamond Storm": ("Rock", 100),
    "Disarming Voice": ("Fairy", 40),
    "Discharge": ("Electric", 80),
    "Dive": ("Water", 80),
    "Dizzy Punch": ("Normal", 70),
    "Doom Desire": ("Steel", 140),
    "Double Hit": ("Normal", 35),
    "Double Iron Bash": ("Steel", 60),
    "Double Kick": ("Fighting", 30),
    "Double-Edge": ("Normal", 120),
    "Dragon Ascent": ("Flying", 120),
    "Dragon Breath": ("Dragon", 60),
    "Dragon Darts": ("Dragon", 50),
    "Dragon Hammer": ("Dragon", 90),
    "Dragon Pulse": ("Dragon", 85),
    "Dragon Rush": ("Dragon", 100),
    "Dragon Tail": ("Dragon", 60),
    "Drain Punch": ("Fighting", 75),
    "Draining Kiss": ("Fairy", 50),
    "Dream Eater": ("Psychic", 100),
    "Drill Peck": ("Flying", 80),
    "Drum Beating": ("Grass", 80),
    "Dual Chop": ("Dragon", 40),
    "Dual Wingbeat": ("Flying", 40),
    "Dynamax Cannon": ("Dragon", 100),
    "Dynamic Punch": ("Fighting", 100),
    "Earth Power": ("Ground", 90),
    "Echoed Voice": ("Normal", 40),
    "Egg Bomb": ("Normal", 100),
    "Electroweb": ("Electric", 55),
    "Ember": ("Fire", 40),
    "Energy Ball": ("Grass", 90),
    "Eruption": ("Fire", 150),
    "Extrasensory": ("Psychic", 80),
    "Extreme Speed": ("Normal", 80),
    "Facade": ("Normal", 70),
    "Fairy Wind": ("Fairy", 40),
    "Fake Out": ("Normal", 40),
    "False Surrender": ("Dark", 80),
    "False Swipe": ("Normal", 40),
    "Feint": ("Normal", 30),
    "Feint Attack": ("Dark", 60),
    "Fell Stinger": ("Bug", 30),
    "Fiery Dance": ("Fire", 80),
    "Fire Blast": ("Fire", 110),
    "Fire Fang": ("Fire", 65),
    "Fire Lash": ("Fire", 80),
    "Fire Pledge": ("Fire", 80),
    "Fire Spin": ("Fire", 35),
    "First Impression": ("Bug", 90),
    "Fishious Rend": ("Water", 85),
    "Flame Burst": ("Fire", 70),
    "Flame Charge": ("Fire", 50),
    "Flame Wheel": ("Fire", 60),
    "Fleur Cannon": ("Fairy", 130),
    "Flip Turn": ("Water", 60),
    "Fly": ("Flying", 90),
    "Flying Press": ("Fighting", 80),
    "Focus Blast": ("Fighting", 120),
    "Force Palm": ("Fighting", 60),
    "Foul Play": ("Dark", 95),
    "Freeze-Dry": ("Ice", 70),
    "Freeze Shock": ("Ice", 140),
    "Frost Breath": ("Ice", 60),
    "Fury Attack": ("Normal", 15),
    "Fury Cutter": ("Bug", 40),
    "Fury Swipes": ("Normal", 18),
    "Fusion Bolt": ("Electric", 100),
    "Fusion Flare": ("Fire", 100),
    "Gear Grind": ("Steel", 50),
    "Giga Drain": ("Grass", 75),
    "Glaciate": ("Ice", 65),
    "Grass Pledge": ("Grass", 80),
    "Grassy Glide": ("Grass", 70),
    "Grav Apple": ("Grass", 80),
    "Gunk Shot": ("Poison", 120),
    "Gust": ("Flying", 40),
    "Hammer Arm": ("Fighting", 100),
    "Head Charge": ("Normal", 120),
    "Head Smash": ("Rock", 150),
    "Headbutt": ("Normal", 70),
    "Heat Wave": ("Fire", 95),
    "Hex": ("Ghost", 65),
    "High Jump Kick": ("Fighting", 130),
    "Hidden Power": ("Normal", 60),
    "Hold Back": ("Normal", 40),
    "Horn Attack": ("Normal", 65),
    "Horn Leech": ("Grass", 75),
    "Hurricane": ("Flying", 110),
    "Hydro Cannon": ("Water", 150),
    "Hydro Pump": ("Water", 110),
    "Hyper Fang": ("Normal", 80),
    "Hyper Voice": ("Normal", 90),
    "Ice Ball": ("Ice", 30),
    "Ice Burn": ("Ice", 140),
    "Ice Fang": ("Ice", 65),
    "Ice Hammer": ("Ice", 100),
    "Ice Shard": ("Ice", 40),
    "Icicle Crash": ("Ice", 85),
    "Icicle Spear": ("Ice", 25),
    "Icy Wind": ("Ice", 55),
    "Incinerate": ("Fire", 60),
    "Inferno": ("Fire", 100),
    "Jaw Lock": ("Dark", 80),
    "Jump Kick": ("Fighting", 100),
    "Karate Chop": ("Fighting", 50),
    "Knock Off": ("Dark", 65),
    "Land's Wrath": ("Ground", 90),
    "Last Resort": ("Normal", 140),
    "Lash Out": ("Dark", 75),
    "Lava Plume": ("Fire", 80),
    "Leafage": ("Grass", 40),
    "Leaf Blade": ("Grass", 90),
    "Leaf Tornado": ("Grass", 65),
    "Leech Life": ("Bug", 20),
    "Lick": ("Ghost", 30),
    "Light of Ruin": ("Fairy", 140),
    "Liquidation": ("Water", 85),
    "Low Sweep": ("Fighting", 65),
    "Lunge": ("Bug", 80),
    "Luster Purge": ("Psychic", 70),
    "Mach Punch": ("Fighting", 40),
    "Magma Storm": ("Fire", 100),
    "Magnet Bomb": ("Steel", 60),
    "Mega Drain": ("Grass", 40),
    "Mega Kick": ("Normal", 120),
    "Mega Punch": ("Normal", 80),
    "Megahorn": ("Bug", 120),
    "Metal Claw": ("Steel", 50),
    "Meteor Assault": ("Fighting", 150),
    "Meteor Beam": ("Rock", 120),
    "Mind Blown": ("Fire", 150),
    "Mirror Shot": ("Steel", 65),
    "Mist Ball": ("Psychic", 70),
    "Misty Explosion": ("Fairy", 100),
    "Moongeist Beam": ("Ghost", 100),
    "Mud Bomb": ("Ground", 65),
    "Mud Shot": ("Ground", 55),
    "Mud-Slap": ("Ground", 20),
    "Muddy Water": ("Water", 90),
    "Multi-Attack": ("Normal", 120),
    "Mystical Fire": ("Fire", 75),
    "Needle Arm": ("Grass", 60),
    "Night Daze": ("Dark", 85),
    "Night Slash": ("Dark", 70),
    "Nuzzle": ("Electric", 20),
    "Oblivion Wing": ("Flying", 80),
    "Octazooka": ("Water", 65),
    "Origin Pulse": ("Water", 110),
    "Overdrive": ("Electric", 80),
    "Parabolic Charge": ("Electric", 50),
    "Pay Day": ("Normal", 40),
    "Payback": ("Dark", 50),
    "Peck": ("Flying", 40),
    "Petal Blizzard": ("Grass", 90),
    "Petal Dance": ("Grass", 120),
    "Photon Geyser": ("Psychic", 100),
    "Pin Missile": ("Bug", 25),
    "Plasma Fists": ("Electric", 100),
    "Play Rough": ("Fairy", 90),
    "Pluck": ("Flying", 60),
    "Poison Fang": ("Poison", 50),
    "Poison Sting": ("Poison", 15),
    "Poison Tail": ("Poison", 50),
    "Pollen Puff": ("Bug", 90),
    "Poltergeist": ("Ghost", 110),
    "Pound": ("Normal", 40),
    "Power Gem": ("Rock", 80),
    "Power Trip": ("Dark", 20),
    "Power Whip": ("Grass", 120),
    "Precipice Blades": ("Ground", 120),
    "Prismatic Laser": ("Psychic", 160),
    "Psybeam": ("Psychic", 65),
    "Psychic Fangs": ("Psychic", 85),
    "Psycho Boost": ("Psychic", 140),
    "Psycho Cut": ("Psychic", 70),
    "Psyshock": ("Psychic", 80),
    "Pursuit": ("Dark", 40),
    "Pyro Ball": ("Fire", 120),
    "Quick Attack": ("Normal", 40),
    "Rage": ("Normal", 20),
    "Rapid Spin": ("Normal", 20),
    "Razor Leaf": ("Grass", 55),
    "Razor Shell": ("Water", 75),
    "Razor Wind": ("Normal", 80),
    "Relic Song": ("Normal", 75),
    "Retaliate": ("Normal", 70),
    "Revelation Dance": ("Normal", 90),
    "Revenge": ("Fighting", 60),
    "Rising Voltage": ("Electric", 70),
    "Rock Blast": ("Rock", 25),
    "Rock Climb": ("Normal", 90),
    "Rock Throw": ("Rock", 50),
    "Rock Wrecker": ("Rock", 150),
    "Rolling Kick": ("Fighting", 60),
    "Rollout": ("Rock", 30),
    "Round": ("Normal", 60),
    "Sacred Fire": ("Fire", 100),
    "Sacred Sword": ("Fighting", 90),
    "Sand Tomb": ("Ground", 35),
    "Scald": ("Water", 80),
    "Scale Shot": ("Dragon", 25),
    "Scorching Sands": ("Ground", 70),
    "Searing Shot": ("Fire", 100),
    "Secret Power": ("Normal", 70),
    "Secret Sword": ("Fighting", 85),
    "Seed Bomb": ("Grass", 80),
    "Seed Flare": ("Grass", 120),
    "Self-Destruct": ("Normal", 200),
    "Shadow Bone": ("Ghost", 85),
    "Shadow Force": ("Ghost", 120),
    "Shadow Punch": ("Ghost", 60),
    "Shadow Sneak": ("Ghost", 40),
    "Shell Side Arm": ("Poison", 90),
    "Signal Beam": ("Bug", 75),
    "Silver Wind": ("Bug", 60),
    "Skitter Smack": ("Bug", 70),
    "Skull Bash": ("Normal", 130),
    "Sky Attack": ("Flying", 140),
    "Sky Drop": ("Flying", 60),
    "Slam": ("Normal", 80),
    "Sludge": ("Poison", 65),
    "Sludge Wave": ("Poison", 95),
    "Smack Down": ("Rock", 50),
    "Smelling Salts": ("Normal", 70),
    "Smog": ("Poison", 30),
    "Snarl": ("Dark", 55),
    "Snap Trap": ("Grass", 35),
    "Snipe Shot": ("Water", 80),
    "Snore": ("Normal", 50),
    "Steam Eruption": ("Water", 110),
    "Steamroller": ("Bug", 65),
    "Steel Beam": ("Steel", 140),
    "Steel Roller": ("Steel", 130),
    "Steel Wing": ("Steel", 70),
    "Stomp": ("Normal", 65),
    "Stored Power": ("Psychic", 20),
    "Storm Throw": ("Fighting", 60),
    "Strange Steam": ("Fairy", 90),
    "Strength": ("Normal", 80),
    "Struggle": ("Normal", 50),
    "Struggle Bug": ("Bug", 50),
    "Submission": ("Fighting", 80),
    "Sucker Punch": ("Dark", 70),
    "Superpower": ("Fighting", 120),
    "Surging Strikes": ("Water", 25),
    "Swift": ("Normal", 60),
    "Synchronoise": ("Psychic", 120),
    "Tackle": ("Normal", 50),
    "Tail Slap": ("Normal", 25),
    "Take Down": ("Normal", 90),
    "Techno Blast": ("Normal", 120),
    "Terrain Pulse": ("Normal", 50),
    "Thousand Arrows": ("Ground", 90),
    "Thousand Waves": ("Ground", 90),
    "Thief": ("Dark", 60),
    "Thrash": ("Normal", 120),
    "Thunder Fang": ("Electric", 65),
    "Thunder Shock": ("Electric", 40),
    "Tri Attack": ("Normal", 80),
    "Triple Axel": ("Ice", 20),
    "Triple Kick": ("Fighting", 10),
    "Twineedle": ("Bug", 25),
    "Twister": ("Dragon", 40),
    "U-turn": ("Bug", 70),
    "Uproar": ("Normal", 90),
    "V-Create": ("Fire", 180),
    "Vacuum Wave": ("Fighting", 40),
    "Venoshock": ("Poison", 65),
    "Vine Whip": ("Grass", 45),
    "Vise Grip": ("Normal", 55),
    "Vital Throw": ("Fighting", 70),
    "Volt Switch": ("Electric", 70),
    "Volt Tackle": ("Electric", 120),
    "Wake-Up Slap": ("Fighting", 70),
    "Water Gun": ("Water", 40),
    "Water Pledge": ("Water", 80),
    "Water Pulse": ("Water", 60),
    "Water Shuriken": ("Water", 15),
    "Water Spout": ("Water", 150),
    "Waterfall": ("Water", 80),
    "Weather Ball": ("Normal", 50),
    "Whirlpool": ("Water", 35),
    "Wicked Blow": ("Dark", 80),
    "Wild Charge": ("Electric", 90),
    "Wood Hammer": ("Grass", 120),
    "Zap Cannon": ("Electric", 120),
    "Zen Headbutt": ("Psychic", 80),
}

